server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ecommerce_db
        username: postgres
        password: tu_contraseña_aquí
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    application:
        name: ecommerce-backend
